version: '3'
services:

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ../php-api:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - development

  db:
    image: mysql
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - development

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ../php-api/:/var/www
    networks:
      - development

  vue:
    build:
      context: .
      dockerfile: Dockerfile-vue
    container_name: vue
    volumes:
      - ../vue-front:/app
    ports:
      - "8081:8080"
    command:
      "npm run serve"

networks:
  development: